server:
  port: 7868

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-jqc1mtsq.sql.tencentcdb.com:26113/springboot_demo
    username: root
    password: fXc6NwWM
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml


api:
  wx:
    env: prod-0grz6agt43c4b51b
    url: https://api.weixin.qq.com
    downloadfile: /tcb/batchdownloadfile
  zt:
    key: wxr88le5ucb8bfoh2
    scale: https://techsz.aoscdn.com/api/tasks/visual/scale
  cp:
    key: b16339409ea775ad
